name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - bokeh
  - bottleneck
  - cartopy
  - cython
  - dill
  - folium
  - geopandas
  - jupyterlab
  - mapclassify
  - networkx
  - nltk
  - numexpr
  - numpy
  - osmnx
  - pillow
  - pip
  - pyproj
  - pysal
  - python == 3.*
  - rasterio
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - textblob
